# Generated by Django 4.0 on 2022-05-15 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_otpcode_phone_number_otpcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
