# Generated by Django 4.0 on 2022-05-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_bloked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bloked_users',
            new_name='blocked_users',
        ),
    ]
