# Generated by Django 4.0 on 2022-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadressmodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
