# Generated by Django 4.0 on 2022-05-04 14:27

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_namemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameModel',
        ),
        migrations.RemoveField(
            model_name='ipadressmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/%Y/%m/%d/', validators=[home.models.Uploaded_size]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', validators=[home.models.Uploaded_size]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%Y/%m/%d/', validators=[home.models.Uploaded_size]),
        ),
    ]
