# Generated by Django 4.0 on 2022-05-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_img'),
        ('home', '0007_alter_commentmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='accounts.user'),
        ),
    ]
