# Generated by Django 4.0 on 2022-05-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_img'),
        ('home', '0009_postmodel_user_likes_likepostview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePostView',
            new_name='LikePostModel',
        ),
    ]
