# Generated by Django 4.0 on 2022-05-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_likepostview_likepostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='LikePostModel',
        ),
    ]
