# Generated by Django 4.0 on 2022-05-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reportpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpostmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpostmodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.postmodel'),
        ),
        migrations.AlterField(
            model_name='reportpostmodel',
            name='report_text',
            field=models.TextField(max_length=470, null=True),
        ),
    ]
